### ISSUE TITLE
How to test if it is working?

### ISSUE THREAD

**Issue by rfht** [flibitijibibo/XNAFileDialog#1]
Hi,

I have 2 games here that use XNAFileDialog - Owlboy and TowerFall. I've compiled it (on OpenBSD) and the games run, but I'm not sure what function XNAFileDialog fulfills. I'm a little concerned that it might not have compiled properly because in TowerFall, when I go to the submenu Workshop -> Browse, nothing happens. This is likely because I don't have the Dark World expansion, but I'd just like to make sure that this is not related to a malfunctioning libXNAFileDialog.
Where do I see best if this library is working?

Thanks.

**Comment by flibitijibibo** [comment]
For Owlboy it's used to select a save from a file path - I think it may be debug mode only, but if not then holding C + H + E should produce a "Load from harddrive" dialog at the main menu.

For TowerFall it's used when loading/saving a map in the editor, so you won't be able to see it without having Dark World.

**Comment by rfht** [comment]
Thanks for the information. Seems to me like the library isn't needed much and not for essential functions of the games. C + H + E didn't work in Owlboy's main menu. I'll prioritize porting other libraries first and will revisit this one when I get the Dark World expansion. Gonna close the issue - thanks.
